package com.sand.ws.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * 
 */
@WebService(name = "RefundServiceDelegate", targetNamespace = "http://www.sand.com.cn/")
public interface RefundServiceDelegate {

	/**
	 * 
	 * @param arg2
	 * @param arg1
	 * @param arg0
	 * @return returns java.lang.String
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "applyGoodsReturnSsl", targetNamespace = "http://www.sand.com.cn/", className = "com.sand.ws.client.ApplyGoodsReturnSsl")
	@ResponseWrapper(localName = "applyGoodsReturnSslResponse", targetNamespace = "http://www.sand.com.cn/", className = "com.sand.ws.client.ApplyGoodsReturnSslResponse")
	public String applyGoodsReturnSsl(
			@WebParam(name = "arg0", targetNamespace = "") String arg0,
			@WebParam(name = "arg1", targetNamespace = "") String arg1,
			@WebParam(name = "arg2", targetNamespace = "") String arg2);

	/**
	 * 
	 * @param arg3
	 * @param arg2
	 * @param arg1
	 * @param arg0
	 * @return returns java.lang.String
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "queryGoodsReturnSsl", targetNamespace = "http://www.sand.com.cn/", className = "com.sand.ws.client.QueryGoodsReturnSsl")
	@ResponseWrapper(localName = "queryGoodsReturnSslResponse", targetNamespace = "http://www.sand.com.cn/", className = "com.sand.ws.client.QueryGoodsReturnSslResponse")
	public String queryGoodsReturnSsl(
			@WebParam(name = "arg0", targetNamespace = "") String arg0,
			@WebParam(name = "arg1", targetNamespace = "") String arg1,
			@WebParam(name = "arg2", targetNamespace = "") String arg2,
			@WebParam(name = "arg3", targetNamespace = "") String arg3);

}
