package com.sand.ws.client;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * <p>
 * An example of how this class may be used:
 * 
 * <pre>
 * RefundService service = new RefundService();
 * RefundServiceDelegate portType = service.getRefund();
 * portType.applyGoodsReturnSsl(...);
 * </pre>
 * 
 * </p>
 * 
 */
@WebServiceClient(name = "RefundService", targetNamespace = "http://www.sand.com.cn/", wsdlLocation = "https://220.248.12.124:36666/CarrefourRefund/Refund?wsdl")
//@WebServiceClient(name = "RefundService", targetNamespace = "http://www.sand.com.cn/", wsdlLocation = "https://180.169.86.124:36666/CarrefourRefund/Refund?wsdl")
//@WebServiceClient(name = "RefundService", targetNamespace = "http://www.sand.com.cn/", wsdlLocation = "https://127.0.0.1/CarrefourRefund/Refund?wsdl")
public class RefundService extends Service {

	private final static URL REFUNDSERVICE_WSDL_LOCATION;
	private final static Logger logger = Logger
			.getLogger(com.sand.ws.client.RefundService.class.getName());

	static {
		URL url = null;
		try {
			URL baseUrl;
			baseUrl = com.sand.ws.client.RefundService.class.getResource(".");
			url = new URL(
					baseUrl,
					"https://220.248.12.124:36666/CarrefourRefund/Refund?wsdl");
//					"https://180.169.86.124:36666/CarrefourRefund/Refund?wsdl");
//					"https://127.0.0.1/CarrefourRefund/Refund?wsdl");
		} catch (MalformedURLException e) {
			logger
					.warning("Failed to create URL for the wsdl Location: 'file:/E:/myeclipse_workspace/CarrefourRefund/WebRoot/WEB-INF/wsdl/RefundService.wsdl', retrying as a local file");
			logger.warning(e.getMessage());
		}
		REFUNDSERVICE_WSDL_LOCATION = url;
	}

	public RefundService(URL wsdlLocation, QName serviceName) {
		super(wsdlLocation, serviceName);
	}

	public RefundService() {
		super(REFUNDSERVICE_WSDL_LOCATION, new QName("http://www.sand.com.cn/",
				"RefundService"));
	}

	/**
	 * 
	 * @return returns RefundServiceDelegate
	 */
	@WebEndpoint(name = "Refund")
	public RefundServiceDelegate getRefund() {
		return super.getPort(new QName("http://www.sand.com.cn/", "Refund"),
				RefundServiceDelegate.class);
	}

}
